/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TapBot } from "./TapBot";
import { TapBotCountArgs } from "./TapBotCountArgs";
import { TapBotFindManyArgs } from "./TapBotFindManyArgs";
import { TapBotFindUniqueArgs } from "./TapBotFindUniqueArgs";
import { DeleteTapBotArgs } from "./DeleteTapBotArgs";
import { TapBotService } from "../tapBot.service";
@graphql.Resolver(() => TapBot)
export class TapBotResolverBase {
  constructor(protected readonly service: TapBotService) {}

  async _tapBotsMeta(
    @graphql.Args() args: TapBotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TapBot])
  async tapBots(@graphql.Args() args: TapBotFindManyArgs): Promise<TapBot[]> {
    return this.service.tapBots(args);
  }

  @graphql.Query(() => TapBot, { nullable: true })
  async tapBot(
    @graphql.Args() args: TapBotFindUniqueArgs
  ): Promise<TapBot | null> {
    const result = await this.service.tapBot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TapBot)
  async deleteTapBot(
    @graphql.Args() args: DeleteTapBotArgs
  ): Promise<TapBot | null> {
    try {
      return await this.service.deleteTapBot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
