/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Friend } from "./Friend";
import { FriendCountArgs } from "./FriendCountArgs";
import { FriendFindManyArgs } from "./FriendFindManyArgs";
import { FriendFindUniqueArgs } from "./FriendFindUniqueArgs";
import { DeleteFriendArgs } from "./DeleteFriendArgs";
import { FriendService } from "../friend.service";
@graphql.Resolver(() => Friend)
export class FriendResolverBase {
  constructor(protected readonly service: FriendService) {}

  async _friendsMeta(
    @graphql.Args() args: FriendCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Friend])
  async friends(@graphql.Args() args: FriendFindManyArgs): Promise<Friend[]> {
    return this.service.friends(args);
  }

  @graphql.Query(() => Friend, { nullable: true })
  async friend(
    @graphql.Args() args: FriendFindUniqueArgs
  ): Promise<Friend | null> {
    const result = await this.service.friend(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Friend)
  async deleteFriend(
    @graphql.Args() args: DeleteFriendArgs
  ): Promise<Friend | null> {
    try {
      return await this.service.deleteFriend(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
