/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Boost } from "./Boost";
import { BoostCountArgs } from "./BoostCountArgs";
import { BoostFindManyArgs } from "./BoostFindManyArgs";
import { BoostFindUniqueArgs } from "./BoostFindUniqueArgs";
import { DeleteBoostArgs } from "./DeleteBoostArgs";
import { BoostService } from "../boost.service";
@graphql.Resolver(() => Boost)
export class BoostResolverBase {
  constructor(protected readonly service: BoostService) {}

  async _boostsMeta(
    @graphql.Args() args: BoostCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Boost])
  async boosts(@graphql.Args() args: BoostFindManyArgs): Promise<Boost[]> {
    return this.service.boosts(args);
  }

  @graphql.Query(() => Boost, { nullable: true })
  async boost(
    @graphql.Args() args: BoostFindUniqueArgs
  ): Promise<Boost | null> {
    const result = await this.service.boost(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Boost)
  async deleteBoost(
    @graphql.Args() args: DeleteBoostArgs
  ): Promise<Boost | null> {
    try {
      return await this.service.deleteBoost(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
