/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SubTask } from "./SubTask";
import { SubTaskCountArgs } from "./SubTaskCountArgs";
import { SubTaskFindManyArgs } from "./SubTaskFindManyArgs";
import { SubTaskFindUniqueArgs } from "./SubTaskFindUniqueArgs";
import { DeleteSubTaskArgs } from "./DeleteSubTaskArgs";
import { SubTaskService } from "../subTask.service";
@graphql.Resolver(() => SubTask)
export class SubTaskResolverBase {
  constructor(protected readonly service: SubTaskService) {}

  async _subTasksMeta(
    @graphql.Args() args: SubTaskCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SubTask])
  async subTasks(
    @graphql.Args() args: SubTaskFindManyArgs
  ): Promise<SubTask[]> {
    return this.service.subTasks(args);
  }

  @graphql.Query(() => SubTask, { nullable: true })
  async subTask(
    @graphql.Args() args: SubTaskFindUniqueArgs
  ): Promise<SubTask | null> {
    const result = await this.service.subTask(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SubTask)
  async deleteSubTask(
    @graphql.Args() args: DeleteSubTaskArgs
  ): Promise<SubTask | null> {
    try {
      return await this.service.deleteSubTask(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
